### ISSUE TITLE
Support for DDL

### ISSUE THREAD

**Issue by rajat-008** [auxten/go-sqldb#2]
Hey @auxten!
First of all congratulations on launching this project!! I'm actually excited to crate the first Issue!!
I was thinking if I could help out in implementing the DDL. I've myself implemented a simple DB in Python and although it did not support DDL, it was possible to create custom tables(all columns are strings) and the start. You can check it out here [NaiveDB](https://github.com/rajat-008/naivedb). 
I'm a newbie to the world of Golang, and therefore would like some guidance from you on how i would go about helping you out.

**Comment by rajat-008** [comment]
And also, since this is a project aimed at helping people understand DB concepts, I was thinking if a course could be spun off around this project? Maybe something that walks through the scratch to complete journey of the DB.

**Comment by auxten** [comment]
The code is here. So, any specific question is welcomed.
