### ISSUE TITLE
Question of execution plan

### ISSUE THREAD

**Issue by yiippee** [auxten/go-sqldb#4]
感谢你开源的项目啊，对于学习数据库很有帮助。
请教一个问题：我看测试用例 SELECT id, username, FROM table WHERE id > 5 AND id < 7 LIMIT 3 查询的时候，过程是，先遍历所有的row，再在内存中过滤，最后返回满足要求的row。   我理解的是应该会先根据where条件在B+树种过滤好再返回吧，而不是在内存中，而且也只会返回  id, username 其他的字段不会返回（这个字段过滤是在内存中吗？还是说在存储层就已经过滤了？）。还是我哪里理解错了？谢谢。

Translation of the question:

>  Thank you for your open source project, it is very helpful for learning database theory.
Ask a question: I see the test case SELECT id, username, FROM table WHERE id> 5 AND id <7 LIMIT 3 When querying, the process is to first traverse all rows, then filter in memory, and finally return the row that meets the requirements. . What I understand is that it should be filtered in the B-Tree based on where conditions before returning, not in memory, and only id will be returned, and other fields of username will not be returned (is this field filtered in memory? Or Say it has been filtered at the storage layer?). Or am I getting it wrong? Thank you.

**Comment by auxten** [comment]
这是一个好问题，“先根据where条件在B+树种过滤”在不同的 where 条件下的 `Physical Execution Plan` 会差别很大。例如：如果 where 条件是 `id > 5` 需要找到 id 为 6 的行，然后递增；`id < 5` 遍历方向是递减；如果 `id in (4, 7, 9)` 又有不同的方式。总而言之，我暂时还没想好一个比较简单容易理解的方式去构建一个真正的 `Physical Execution Planner`，所以代码中采用的是最为简单粗暴的全部遍历的方式。

English version answer:

> This is a good question. The `Physical Execution Plan` under different where conditions will be very different. For example: if the where condition is `id> 5`, you need to find the row with id 6 and then increase; `id <5` the traversal direction is decreasing; if `id in (4, 7, 9)`, there are different ways. All in all, I haven't thought of a relatively simple and easy-to-understand way to build a real `Physical Execution Planner`, so the code is the simplest and rude all-traversal method.
